[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
evm_version = "shanghai"

[rpc_endpoints]
skale = "${SKALE_RPC_URL}"

[etherscan]
# SKALE doesn't use Etherscan verification
